### ISSUE TITLE
最新版的Vue-cli中build目录中的文件不一样

### ISSUE THREAD

**Issue by ZhangWren** [Hxvin/vue-home#3]
![tim 20180319105515](https://user-images.githubusercontent.com/25240164/37575794-0db1b738-2b64-11e8-9e0c-f1e51bc93a0e.png)
如图，红框中的两个js在最新版vue-cli中已经不存在，那之前在这两个文件中做的修改，如何适配到最新版的vue-cli中呢，请指教

**Comment by aermin** [comment]
这个直接根据关键词搜索下要修改的地方哦，换汤不换药。 或者可以直接使用旧版本的vue-cli就好。

**Comment by ZhangWren** [comment]
@hxvin 不好意思啊，刚接触vue不久，我现在已经是最新的版本了，我没查到怎么使用旧版本，能指点下吗，谢谢谢谢

**Comment by aermin** [comment]
@SamoZ   https://segmentfault.com/q/1010000013181990?utm_source=index-hottest 看这个的方法试试哈  其实好像就改了assetsPublicPath （bulid中的） ，而且这个还是你项目做完打包静态资源时才涉及到的 ；要是端口号被占用了就换另外一个就行(一般不回)。 建议看看webpack的文档，看下你就较能明白vue-cli的配置了

**Comment by ZhangWren** [comment]
@hxvin 我卸载重新安装指定版本，我已经尝试了3种版本了，都是报这个错误，心态有点炸。。。。能加你的QQ或者啥的嘛
![tim 20180320100613](https://user-images.githubusercontent.com/25240164/37632049-4bbc7ac2-2c27-11e8-9f55-84306723a78e.png)

**Comment by ZhangWren** [comment]
@hxvin  知道问题所在了，麻烦了

**Comment by aermin** [comment]
@SamoZ  没事  加油😄
